dist: trusty
language: c
sudo: false
addons:
  apt:
    packages:
      - locales
      - language-pack-de
      - re2c
      - libgmp-dev
      - libicu-dev
      - libmcrypt-dev
      - libtidy-dev
      - libenchant-dev
      - libaspell-dev
      - libpspell-dev
      - librecode-dev
      - libsasl2-dev
      - libxpm-dev
      - libt1-dev

notifications:
    email: 
       on_failure: change
    irc:
      template:
        - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} -  Change view : %{compare_url} - Build details : %{build_url}"
      channels:
        - "irc.efnet.org#php.pecl"
      on_success: change
      on_failure: always

cache: 
    - apt

env:
    global:
      - MYSQL_TEST_HOST=127.0.0.1
      - MYSQL_TEST_USER=travis
      - PDO_MYSQL_TEST_DSN="mysql:host=127.0.0.1;dbname=test"
      - PDO_MYSQL_TEST_USER=travis
      - PDO_MYSQL_TEST_PASS=
      - PDO_MYSQL_TEST_HOST=127.0.0.1
      - REPORT_EXIT_STATUS=1
    matrix:
      - ENABLE_MAINTAINER_ZTS=0 ENABLE_DEBUG=0
      - ENABLE_MAINTAINER_ZTS=1 ENABLE_DEBUG=1

before_script:
    # Compile PHP
    - ./travis/compile.sh
    # Setup Extensions 
    - . ./travis/ext/mysql/setup.sh
    - . ./travis/ext/mysqli/setup.sh
    - . ./travis/ext/pdo_mysql/setup.sh
    - . ./travis/ext/pgsql/setup.sh
    - . ./travis/ext/pdo_pgsql/setup.sh

# Run PHPs run-tests.php 
script:
    - ./sapi/cli/php run-tests.php -p `pwd`/sapi/cli/php $(if [ $ENABLE_DEBUG == 1 ]; then echo "-d opcache.enable_cli=1 -d zend_extension=`pwd`/modules/opcache.so"; fi) -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" --offline --show-diff --set-timeout 120
