#!/bin/sh
set -e

# Author: Robie Basak <robie.basak@ubuntu.com>

cd "$ADTTMP"
cat > hello.php <<EOT
<?php echo "Hello, world!\n"; ?>
EOT

result=`php@PHP_VERSION@ hello.php`
test "$result" = "Hello, world!"
