#!/bin/sh
/usr/sbin/php-fpm@PHP_VERSION@ -t >/dev/null 2>/dev/null
ret=$?
if [ "$ret" -ne 0 ]; then
    echo "PHP FPM configuration is broken:"
    /usr/sbin/php-fpm@PHP_VERSION@ -t
    exit 1
fi
exit 0
